Release 4.1.0
voxpupuli/puppet-rhsm pull request #116
Opened 2021-09-25 15:42 UTC by bastelfreak

#### Pull Request (PR) description

#### This Pull Request (PR) fixes the following issues

2021-09-25 23:39 UTC, kenyon approved these changes

2021-09-26 15:19 UTC, alexjfisher requested changes

2021-09-26 15:19 UTC, alexjfisher commented on README.md
> +[![Puppet Forge](https://img.shields.io/puppetforge/v/puppet/lldpd.svg)](https://forge.puppetlabs.com/puppet/lldpd)
Which module is this?

2021-09-27 18:45 UTC, alexjfisher approved these changes

2021-09-27 18:47 UTC, merged